In [1]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [3]:
# multivariate output data prep
from numpy import array
from numpy import hstack

# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

In [7]:
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

In [9]:
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps = 3
dataset

array([[ 10,  15,  25],
       [ 20,  25,  45],
       [ 30,  35,  65],
       [ 40,  45,  85],
       [ 50,  55, 105],
       [ 60,  65, 125],
       [ 70,  75, 145],
       [ 80,  85, 165],
       [ 90,  95, 185]])

In [10]:
# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

(6, 3, 3) (6, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [40 45 85]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [ 50  55 105]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [ 60  65 125]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [ 70  75 145]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [ 80  85 165]
[[ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]] [ 90  95 185]


In [12]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

Using TensorFlow backend.


In [16]:
model = Sequential()
model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=X.shape[1:]))
model.add(LSTM(100, activation='relu'))
model.add(Dense(X.shape[-1]))
model.compile(optimizer='adam', loss='mse')

In [18]:
model.fit(X, y, epochs=400, verbose=True)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/400





6/6 [==============================] - 7s 1s/step - loss: 10125.2217
Epoch 2/400
6/6 [==============================] - 0s 5ms/step - loss: 9557.7139
Epoch 3/400
6/6 [==============================] - 0s 9ms/step - loss: 9078.0820
Epoch 4/400
6/6 [==============================] - 0s 12ms/step - loss: 8727.5127
Epoch 5/400
6/6 [==============================] - 0s 8ms/step - loss: 8392.3652
Epoch 6/400
6/6 [==============================] - 0s 7ms/step - loss: 8030.8159
Epoch 7/400
6/6 [==============================] - 0s 5ms/step - loss: 7628.0522
Epoch 8/400
6/6 [==============================] - 0s 6ms/step - loss: 7268.5610
Epoch 9/400
6/6 [==============================] - 0s 6ms/step - loss: 6862.6953
Epoch 10/400
6/6 [==============================] - 0s 6ms/step - loss: 6442.4297
Epoch 11/400
6/6 [==============================] - 0s 6ms/step - loss: 5994.4741
Epoc

Epoch 77/400
6/6 [==============================] - 0s 9ms/step - loss: 0.4679
Epoch 78/400
6/6 [==============================] - 0s 10ms/step - loss: 0.3011
Epoch 79/400
6/6 [==============================] - 0s 11ms/step - loss: 0.5299
Epoch 80/400
6/6 [==============================] - 0s 10ms/step - loss: 0.6235
Epoch 81/400
6/6 [==============================] - 0s 12ms/step - loss: 0.4245
Epoch 82/400
6/6 [==============================] - 0s 8ms/step - loss: 0.2904
Epoch 83/400
6/6 [==============================] - 0s 6ms/step - loss: 0.3839
Epoch 84/400
6/6 [==============================] - 0s 6ms/step - loss: 0.4207
Epoch 85/400
6/6 [==============================] - 0s 6ms/step - loss: 0.2620
Epoch 86/400
6/6 [==============================] - 0s 5ms/step - loss: 0.1534
Epoch 87/400
6/6 [==============================] - 0s 5ms/step - loss: 0.2265
Epoch 88/400
6/6 [==============================] - 0s 5ms/step - loss: 0.2951
Epoch 89/400
6/6 [==============================

Epoch 180/400
6/6 [==============================] - 0s 7ms/step - loss: 0.0056
Epoch 181/400
6/6 [==============================] - 0s 6ms/step - loss: 0.0055
Epoch 182/400
6/6 [==============================] - 0s 10ms/step - loss: 0.0055
Epoch 183/400
6/6 [==============================] - 0s 6ms/step - loss: 0.0054
Epoch 184/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0053
Epoch 185/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0052
Epoch 186/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0051
Epoch 187/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0050
Epoch 188/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0049
Epoch 189/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0049
Epoch 190/400
6/6 [==============================] - 0s 11ms/step - loss: 0.0048
Epoch 191/400
6/6 [==============================] - 0s 17ms/step - loss: 0.0047
Epoch 192/400
6/6 [==================

Epoch 282/400
6/6 [==============================] - 0s 7ms/step - loss: 0.0013
Epoch 283/400
6/6 [==============================] - 0s 7ms/step - loss: 0.0013
Epoch 284/400
6/6 [==============================] - 0s 6ms/step - loss: 0.0013
Epoch 285/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0013
Epoch 286/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0013
Epoch 287/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0012
Epoch 288/400
6/6 [==============================] - 0s 6ms/step - loss: 0.0012
Epoch 289/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0012
Epoch 290/400
6/6 [==============================] - 0s 5ms/step - loss: 0.0012
Epoch 291/400
6/6 [==============================] - 0s 6ms/step - loss: 0.0012
Epoch 292/400
6/6 [==============================] - 0s 10ms/step - loss: 0.0012
Epoch 293/400
6/6 [==============================] - 0s 10ms/step - loss: 0.0012
Epoch 294/400
6/6 [===================

Epoch 381/400
6/6 [==============================] - 0s 7ms/step - loss: 4.5382e-04
Epoch 382/400
6/6 [==============================] - 0s 6ms/step - loss: 4.4981e-04
Epoch 383/400
6/6 [==============================] - 0s 5ms/step - loss: 4.4576e-04
Epoch 384/400
6/6 [==============================] - 0s 7ms/step - loss: 4.4181e-04
Epoch 385/400
6/6 [==============================] - 0s 6ms/step - loss: 4.3782e-04
Epoch 386/400
6/6 [==============================] - 0s 5ms/step - loss: 4.3388e-04
Epoch 387/400
6/6 [==============================] - 0s 5ms/step - loss: 4.3005e-04
Epoch 388/400
6/6 [==============================] - 0s 5ms/step - loss: 4.2639e-04
Epoch 389/400
6/6 [==============================] - 0s 5ms/step - loss: 4.2261e-04
Epoch 390/400
6/6 [==============================] - 0s 5ms/step - loss: 4.1894e-04
Epoch 391/400
6/6 [==============================] - 0s 6ms/step - loss: 4.1532e-04
Epoch 392/400
6/6 [==============================] - 0s 6ms/step - loss: 4.1